DROP DATABASE IF EXISTS dsw_phpcrud;
CREATE DATABASE dsw_phpcrud;

CREATE TABLE data (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) DEFAULT NULL,
    state VARCHAR(150) DEFAULT NULL,
    city VARCHAR(150) DEFAULT NULL,
    PRIMARY KEY (id)
);
